# Generated by Django 3.0.2 on 2020-02-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200127_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
