# Generated by Django 3.0.2 on 2020-02-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200209_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lent_date',
            field=models.DateTimeField(null=True),
        ),
    ]
