# Generated by Django 3.0.2 on 2020-03-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200301_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.CharField(choices=[('d', 'default'), ('t', 'trashed'), ('a', 'archived')], default='d', max_length=1),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[('d', 'default'), ('t', 'trashed'), ('a', 'archived')], default='d', max_length=1),
        ),
    ]
