# Generated by Django 3.0.7 on 2020-07-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_locationprintlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('trash_item', 'Can trash item'), ('lend_item', 'Can lend item')]},
        ),
    ]
